# Assume `flag_str` contains the string that was generated by the original code -> Opens enc
flag_str = open("enc").read()
flag = ""

for i in range(len(flag_str)):
    # Extract the high and low bytes of the encoded character
    high_byte = (ord(flag_str[i]) >> 8) & 0xFF
    low_byte = ord(flag_str[i]) & 0xFF
    
    # Convert the high and low bytes to characters and append them to the flag
    flag += chr(high_byte) + chr(low_byte)
print(flag)